steps:
- name: 'ubuntu'
  script: |
    echo "Hello, world! The time is $(date)." > quickstart.sh
    echo "FROM alpine" > Dockerfile
    echo "COPY quickstart.sh /" >> Dockerfile
    echo "CMD ["/quickstart.sh"]" >> Dockerfile
- name: 'docker'
  args: ['build', '-t', 'us-docker.pkg.dev/argo-local-giangnguyen/trigger-test/unique725:my-tag', '.']
- name: 'python:3.10.7-slim-bullseye'
  entrypoint: 'pip'
  args: ['download', 'sampleproject==2.0.0', '-v']
- name: 'ubuntu'
  script: |
    mkdir dist 
    mv -v peppercorn-0.6-py3-none-any.whl dist/peppercorn-0.42-py3-none-any.whl
    mv -v sampleproject-2.0.0-py3-none-any.whl dist/sampleproject-2.0.42-py3-none-any.whl
artifacts:
  images: ['us-docker.pkg.dev/argo-local-giangnguyen/trigger-test/unique725:my-tag']
options:
  requested_verify_option: VERIFIED
queueTtl: '10m'
