steps:
- name: 'ubuntu'
  script: |
    echo Hello, world! The time is Tue Aug 8 07:58:55 PM UTC 2023. > quickstart.sh
    echo FROM alpine > Dockerfile
    echo COPY quickstart.sh / >> Dockerfile
    echo CMD [/quickstart.sh] >> Dockerfile
- name: 'docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/docker-prov-repo/unique-pr:my-tag', '.']
- name: 'python:3.10.7-slim-bullseye'
  entrypoint: 'pip'
  args: ['download', 'sampleproject==2.0.0', '-v']
artifacts:
  images: ['$LOCATION-docker.pkg.dev/$PROJECT_ID/docker-prov-repo/unique-pr:my-tag']
options:
  requested_verify_option: VERIFIED
queueTtl: '10m'
